spring:
  application:
    name: containershield

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

trivy:
  server:
    url: ${TRIVY_SERVER_URL}