spring:
  application:
    name: containershield

  datasource:
    url: jdbc:postgresql://localhost:5432/containershield
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

trivy:
  server:
    url: ${TRIVY_SERVER_URL:http://containershield-trivy:4954}